// Texto del correo "Olvidé mi clave" del personal (director, supra-control, médico, administrativo), en los nueve idiomas.
import type { MailLanguage } from "./mail-i18n";

export type StaffResetText = { subject: string; hello: (name?: string) => string; intro: string; button: string; note: string; ignore: string };

export const STAFF_RESET_TEXT: Record<MailLanguage, StaffResetText> = {
  es: { subject: "Recupera tu clave - Clinivista", hello: (n) => (n ? `Hola ${n},` : "Hola,"), intro: "Recibimos una solicitud para cambiar la clave de tu cuenta del panel.", button: "Elegir una clave nueva", note: "El enlace sirve una vez y vence en 1 hora.", ignore: "Si no fuiste tú, ignora este correo: tu clave sigue igual." },
  en: { subject: "Reset your password - Clinivista", hello: (n) => (n ? `Hello ${n},` : "Hello,"), intro: "We received a request to change the password of your panel account.", button: "Choose a new password", note: "The link works once and expires in 1 hour.", ignore: "If it wasn't you, ignore this email: your password stays the same." },
  pt: { subject: "Recupere sua senha - Clinivista", hello: (n) => (n ? `Olá ${n},` : "Olá,"), intro: "Recebemos um pedido para alterar a senha da sua conta do painel.", button: "Escolher uma nova senha", note: "O link funciona uma vez e expira em 1 hora.", ignore: "Se não foi você, ignore este e-mail: sua senha continua a mesma." },
  fr: { subject: "Réinitialisez votre mot de passe - Clinivista", hello: (n) => (n ? `Bonjour ${n},` : "Bonjour,"), intro: "Nous avons reçu une demande de changement du mot de passe de votre compte du panneau.", button: "Choisir un nouveau mot de passe", note: "Le lien ne fonctionne qu'une fois et expire dans 1 heure.", ignore: "Si ce n'était pas vous, ignorez cet e-mail : votre mot de passe reste inchangé." },
  de: { subject: "Passwort zurücksetzen - Clinivista", hello: (n) => (n ? `Hallo ${n},` : "Hallo,"), intro: "Wir haben eine Anfrage zum Ändern des Passworts Ihres Panel-Kontos erhalten.", button: "Neues Passwort wählen", note: "Der Link funktioniert nur einmal und läuft in 1 Stunde ab.", ignore: "Falls Sie das nicht waren, ignorieren Sie diese E-Mail: Ihr Passwort bleibt unverändert." },
  it: { subject: "Recupera la tua password - Clinivista", hello: (n) => (n ? `Ciao ${n},` : "Ciao,"), intro: "Abbiamo ricevuto una richiesta per cambiare la password del tuo account del pannello.", button: "Scegli una nuova password", note: "Il link funziona una sola volta e scade tra 1 ora.", ignore: "Se non sei stato tu, ignora questa e-mail: la tua password resta invariata." },
  tr: { subject: "Şifrenizi sıfırlayın - Clinivista", hello: (n) => (n ? `Merhaba ${n},` : "Merhaba,"), intro: "Panel hesabınızın şifresini değiştirmek için bir istek aldık.", button: "Yeni şifre seç", note: "Bağlantı yalnızca bir kez çalışır ve 1 saat içinde sona erer.", ignore: "Bu işlemi siz yapmadıysanız bu e-postayı yok sayın: şifreniz değişmez." },
  ar: { subject: "استعادة كلمة المرور - Clinivista", hello: (n) => (n ? `مرحباً ${n}،` : "مرحباً،"), intro: "تلقينا طلباً لتغيير كلمة مرور حسابك في لوحة التحكم.", button: "اختيار كلمة مرور جديدة", note: "يعمل الرابط مرة واحدة فقط وتنتهي صلاحيته خلال ساعة واحدة.", ignore: "إذا لم تكن أنت، تجاهل هذه الرسالة: ستبقى كلمة مرورك كما هي." },
  zh: { subject: "重置您的密码 - Clinivista", hello: (n) => (n ? `您好 ${n}，` : "您好，"), intro: "我们收到了更改您的控制面板账户密码的请求。", button: "设置新密码", note: "该链接仅可使用一次，1 小时后失效。", ignore: "如果这不是您本人的操作，请忽略此邮件：您的密码不会改变。" },
};
