import type { LangCode } from "@/lib/language";

export type HelpBlock =
  | { t: "p" | "note" | "tip" | "warn" | "h3"; text: string }
  | { t: "ul"; items: string[] }
  | { t: "legend"; items: string[]; caption?: string }
  | { t: "table"; head: string[]; rows: string[][]; widths?: number[] };
export type HelpSection = { id: string; title: string; blocks: HelpBlock[] };
export type HelpManual = { patient: HelpSection[]; staff: HelpSection[] };

// Cada idioma se carga solo cuando se abre la ayuda (no pesa en el resto de la app).
const loaders = import.meta.glob<{ default: HelpManual }>("./help/manual-*.json");

export async function loadManual(lang: LangCode): Promise<HelpManual> {
  const load = loaders[`./help/manual-${lang}.json`] ?? loaders["./help/manual-es.json"];
  return (await load!()).default;
}

export type HelpText = {
  nav: string; title: string; subtitle: string; tabManual: string; tabSupport: string;
  partStaff: string; partPatient: string; search: string; noResults: string; sections: string; loading: string;
  chatTitle: string; chatIntro: string; chatPlaceholder: string; send: string; chatEmpty: string;
  you: string; team: string; sendError: string; loadError: string; hint: string;
};

export const HELP_TEXT: Record<LangCode, HelpText> = {
  es: { nav: "Ayuda", title: "Centro de ayuda", subtitle: "Manual de uso y soporte en línea", tabManual: "Manual", tabSupport: "Soporte", partStaff: "Para el personal de la clínica", partPatient: "Para el paciente", search: "Buscar en el manual…", noResults: "No hay resultados.", sections: "Secciones", loading: "Cargando…", chatTitle: "Chat con soporte", chatIntro: "Escríbenos y te responderemos aquí mismo. Si no estamos en línea, verás la respuesta cuando vuelvas.", chatPlaceholder: "Escribe tu mensaje…", send: "Enviar", chatEmpty: "Aún no hay mensajes. ¿En qué podemos ayudarte?", you: "Tú", team: "Soporte Clinivista", sendError: "No se pudo enviar el mensaje.", loadError: "No se pudo cargar la conversación.", hint: "Enter para enviar · Mayús+Enter para salto de línea" },
  en: { nav: "Help", title: "Help center", subtitle: "User manual and live support", tabManual: "Manual", tabSupport: "Support", partStaff: "For clinic staff", partPatient: "For patients", search: "Search the manual…", noResults: "No results.", sections: "Sections", loading: "Loading…", chatTitle: "Chat with support", chatIntro: "Write to us and we will reply right here. If we are offline, you will see the answer when you come back.", chatPlaceholder: "Type your message…", send: "Send", chatEmpty: "No messages yet. How can we help you?", you: "You", team: "Clinivista Support", sendError: "The message could not be sent.", loadError: "The conversation could not be loaded.", hint: "Enter to send · Shift+Enter for a new line" },
  pt: { nav: "Ajuda", title: "Central de ajuda", subtitle: "Manual de uso e suporte online", tabManual: "Manual", tabSupport: "Suporte", partStaff: "Para a equipe da clínica", partPatient: "Para o paciente", search: "Buscar no manual…", noResults: "Nenhum resultado.", sections: "Seções", loading: "Carregando…", chatTitle: "Chat com o suporte", chatIntro: "Escreva para nós e responderemos aqui mesmo. Se não estivermos online, você verá a resposta quando voltar.", chatPlaceholder: "Escreva sua mensagem…", send: "Enviar", chatEmpty: "Ainda não há mensagens. Como podemos ajudar?", you: "Você", team: "Suporte Clinivista", sendError: "Não foi possível enviar a mensagem.", loadError: "Não foi possível carregar a conversa.", hint: "Enter para enviar · Shift+Enter para nova linha" },
  fr: { nav: "Aide", title: "Centre d'aide", subtitle: "Manuel d'utilisation et assistance en ligne", tabManual: "Manuel", tabSupport: "Assistance", partStaff: "Pour le personnel de la clinique", partPatient: "Pour le patient", search: "Rechercher dans le manuel…", noResults: "Aucun résultat.", sections: "Sections", loading: "Chargement…", chatTitle: "Chat avec l'assistance", chatIntro: "Écrivez-nous et nous vous répondrons ici. Si nous sommes hors ligne, vous verrez la réponse à votre retour.", chatPlaceholder: "Écrivez votre message…", send: "Envoyer", chatEmpty: "Aucun message pour l'instant. Comment pouvons-nous vous aider ?", you: "Vous", team: "Assistance Clinivista", sendError: "Le message n'a pas pu être envoyé.", loadError: "La conversation n'a pas pu être chargée.", hint: "Entrée pour envoyer · Maj+Entrée pour un saut de ligne" },
  de: { nav: "Hilfe", title: "Hilfezentrum", subtitle: "Benutzerhandbuch und Live-Support", tabManual: "Handbuch", tabSupport: "Support", partStaff: "Für das Klinikpersonal", partPatient: "Für Patienten", search: "Im Handbuch suchen…", noResults: "Keine Ergebnisse.", sections: "Abschnitte", loading: "Wird geladen…", chatTitle: "Chat mit dem Support", chatIntro: "Schreiben Sie uns, wir antworten direkt hier. Wenn wir offline sind, sehen Sie die Antwort bei Ihrer Rückkehr.", chatPlaceholder: "Nachricht schreiben…", send: "Senden", chatEmpty: "Noch keine Nachrichten. Wie können wir helfen?", you: "Sie", team: "Clinivista-Support", sendError: "Die Nachricht konnte nicht gesendet werden.", loadError: "Die Unterhaltung konnte nicht geladen werden.", hint: "Enter zum Senden · Umschalt+Enter für neue Zeile" },
  it: { nav: "Aiuto", title: "Centro assistenza", subtitle: "Manuale d'uso e supporto online", tabManual: "Manuale", tabSupport: "Supporto", partStaff: "Per il personale della clinica", partPatient: "Per il paziente", search: "Cerca nel manuale…", noResults: "Nessun risultato.", sections: "Sezioni", loading: "Caricamento…", chatTitle: "Chat con il supporto", chatIntro: "Scrivici e ti risponderemo qui. Se siamo offline, vedrai la risposta quando torni.", chatPlaceholder: "Scrivi il tuo messaggio…", send: "Invia", chatEmpty: "Ancora nessun messaggio. Come possiamo aiutarti?", you: "Tu", team: "Supporto Clinivista", sendError: "Impossibile inviare il messaggio.", loadError: "Impossibile caricare la conversazione.", hint: "Invio per inviare · Maiusc+Invio per andare a capo" },
  tr: { nav: "Yardım", title: "Yardım merkezi", subtitle: "Kullanım kılavuzu ve çevrimiçi destek", tabManual: "Kılavuz", tabSupport: "Destek", partStaff: "Klinik personeli için", partPatient: "Hasta için", search: "Kılavuzda ara…", noResults: "Sonuç yok.", sections: "Bölümler", loading: "Yükleniyor…", chatTitle: "Destek ile sohbet", chatIntro: "Bize yazın, yanıtı burada vereceğiz. Çevrimdışıysak geri döndüğünüzde yanıtı görürsünüz.", chatPlaceholder: "Mesajınızı yazın…", send: "Gönder", chatEmpty: "Henüz mesaj yok. Size nasıl yardımcı olabiliriz?", you: "Siz", team: "Clinivista Destek", sendError: "Mesaj gönderilemedi.", loadError: "Konuşma yüklenemedi.", hint: "Göndermek için Enter · Yeni satır için Shift+Enter" },
  ar: { nav: "المساعدة", title: "مركز المساعدة", subtitle: "دليل الاستخدام والدعم المباشر", tabManual: "الدليل", tabSupport: "الدعم", partStaff: "لموظفي العيادة", partPatient: "للمريض", search: "ابحث في الدليل…", noResults: "لا توجد نتائج.", sections: "الأقسام", loading: "جارٍ التحميل…", chatTitle: "الدردشة مع الدعم", chatIntro: "اكتب لنا وسنرد عليك هنا. إذا لم نكن متصلين فسترى الرد عند عودتك.", chatPlaceholder: "اكتب رسالتك…", send: "إرسال", chatEmpty: "لا توجد رسائل بعد. كيف يمكننا مساعدتك؟", you: "أنت", team: "دعم Clinivista", sendError: "تعذّر إرسال الرسالة.", loadError: "تعذّر تحميل المحادثة.", hint: "Enter للإرسال · Shift+Enter لسطر جديد" },
  zh: { nav: "帮助", title: "帮助中心", subtitle: "使用手册与在线支持", tabManual: "手册", tabSupport: "支持", partStaff: "面向诊所人员", partPatient: "面向患者", search: "在手册中搜索…", noResults: "没有结果。", sections: "章节", loading: "加载中…", chatTitle: "与支持团队聊天", chatIntro: "给我们留言，我们会在这里回复。如果我们不在线，您回来时就能看到回复。", chatPlaceholder: "输入您的消息…", send: "发送", chatEmpty: "暂无消息。有什么可以帮您？", you: "您", team: "Clinivista 支持", sendError: "消息发送失败。", loadError: "无法加载对话。", hint: "按 Enter 发送 · Shift+Enter 换行" },
};
