import type { LangCode } from "@/lib/language";

export type StaffResetText = {
  forgotLink: string; forgotTitle: string; forgotSub: string; send: string; sending: string; sent: string; back: string;
  resetTitle: string; newPassword: string; repeatPassword: string; mismatch: string; minLength: string; save: string;
  invalid: string; done: string; goLogin: string;
};

export const STAFF_RESET_TEXT: Record<LangCode, StaffResetText> = {
  es: { forgotLink: "¿Olvidaste tu contraseña?", forgotTitle: "Recupera tu contraseña", forgotSub: "Escribe tu correo y te enviaremos un enlace para elegir una nueva.", send: "Enviar enlace", sending: "Enviando...", sent: "Si el correo corresponde a una cuenta activa, te enviamos un enlace. Revisa también la carpeta de spam. Vence en 1 hora.", back: "Volver a ingresar", resetTitle: "Elige una contraseña nueva", newPassword: "Contraseña nueva", repeatPassword: "Repite la contraseña", mismatch: "Las contraseñas no coinciden.", minLength: "Mínimo 8 caracteres.", save: "Guardar contraseña", invalid: "El enlace no es válido o ya venció. Pide uno nuevo.", done: "Listo, tu contraseña fue cambiada. Ya puedes ingresar.", goLogin: "Ir a ingresar" },
  en: { forgotLink: "Forgot your password?", forgotTitle: "Recover your password", forgotSub: "Enter your email and we'll send you a link to choose a new one.", send: "Send link", sending: "Sending...", sent: "If the email belongs to an active account, we sent you a link. Check your spam folder too. It expires in 1 hour.", back: "Back to sign in", resetTitle: "Choose a new password", newPassword: "New password", repeatPassword: "Repeat the password", mismatch: "The passwords don't match.", minLength: "At least 8 characters.", save: "Save password", invalid: "The link is invalid or has expired. Request a new one.", done: "Done, your password was changed. You can sign in now.", goLogin: "Go to sign in" },
  pt: { forgotLink: "Esqueceu sua senha?", forgotTitle: "Recupere sua senha", forgotSub: "Digite seu e-mail e enviaremos um link para escolher uma nova.", send: "Enviar link", sending: "Enviando...", sent: "Se o e-mail corresponder a uma conta ativa, enviamos um link. Verifique também o spam. Ele expira em 1 hora.", back: "Voltar ao login", resetTitle: "Escolha uma nova senha", newPassword: "Nova senha", repeatPassword: "Repita a senha", mismatch: "As senhas não coincidem.", minLength: "Mínimo de 8 caracteres.", save: "Salvar senha", invalid: "O link é inválido ou expirou. Solicite um novo.", done: "Pronto, sua senha foi alterada. Você já pode entrar.", goLogin: "Ir para o login" },
  fr: { forgotLink: "Mot de passe oublié ?", forgotTitle: "Récupérez votre mot de passe", forgotSub: "Saisissez votre e-mail et nous vous enverrons un lien pour en choisir un nouveau.", send: "Envoyer le lien", sending: "Envoi...", sent: "Si l'e-mail correspond à un compte actif, nous vous avons envoyé un lien. Vérifiez aussi vos spams. Il expire dans 1 heure.", back: "Retour à la connexion", resetTitle: "Choisissez un nouveau mot de passe", newPassword: "Nouveau mot de passe", repeatPassword: "Répétez le mot de passe", mismatch: "Les mots de passe ne correspondent pas.", minLength: "Au moins 8 caractères.", save: "Enregistrer le mot de passe", invalid: "Le lien est invalide ou a expiré. Demandez-en un nouveau.", done: "C'est fait, votre mot de passe a été modifié. Vous pouvez vous connecter.", goLogin: "Aller à la connexion" },
  de: { forgotLink: "Passwort vergessen?", forgotTitle: "Passwort wiederherstellen", forgotSub: "Geben Sie Ihre E-Mail ein, wir senden Ihnen einen Link zum Festlegen eines neuen Passworts.", send: "Link senden", sending: "Wird gesendet...", sent: "Gehört die E-Mail zu einem aktiven Konto, haben wir Ihnen einen Link gesendet. Prüfen Sie auch den Spam-Ordner. Er läuft in 1 Stunde ab.", back: "Zurück zur Anmeldung", resetTitle: "Neues Passwort wählen", newPassword: "Neues Passwort", repeatPassword: "Passwort wiederholen", mismatch: "Die Passwörter stimmen nicht überein.", minLength: "Mindestens 8 Zeichen.", save: "Passwort speichern", invalid: "Der Link ist ungültig oder abgelaufen. Fordern Sie einen neuen an.", done: "Fertig, Ihr Passwort wurde geändert. Sie können sich jetzt anmelden.", goLogin: "Zur Anmeldung" },
  it: { forgotLink: "Hai dimenticato la password?", forgotTitle: "Recupera la tua password", forgotSub: "Inserisci la tua e-mail e ti invieremo un link per sceglierne una nuova.", send: "Invia link", sending: "Invio...", sent: "Se l'e-mail corrisponde a un account attivo, ti abbiamo inviato un link. Controlla anche lo spam. Scade tra 1 ora.", back: "Torna all'accesso", resetTitle: "Scegli una nuova password", newPassword: "Nuova password", repeatPassword: "Ripeti la password", mismatch: "Le password non coincidono.", minLength: "Almeno 8 caratteri.", save: "Salva password", invalid: "Il link non è valido o è scaduto. Richiedine uno nuovo.", done: "Fatto, la tua password è stata cambiata. Ora puoi accedere.", goLogin: "Vai all'accesso" },
  tr: { forgotLink: "Şifrenizi mi unuttunuz?", forgotTitle: "Şifrenizi kurtarın", forgotSub: "E-postanızı yazın, yeni bir şifre seçmeniz için size bir bağlantı gönderelim.", send: "Bağlantı gönder", sending: "Gönderiliyor...", sent: "E-posta etkin bir hesaba aitse size bir bağlantı gönderdik. Spam klasörünüzü de kontrol edin. 1 saat içinde sona erer.", back: "Girişe dön", resetTitle: "Yeni bir şifre seçin", newPassword: "Yeni şifre", repeatPassword: "Şifreyi tekrarlayın", mismatch: "Şifreler eşleşmiyor.", minLength: "En az 8 karakter.", save: "Şifreyi kaydet", invalid: "Bağlantı geçersiz veya süresi dolmuş. Yeni bir tane isteyin.", done: "Tamam, şifreniz değiştirildi. Artık giriş yapabilirsiniz.", goLogin: "Girişe git" },
  ar: { forgotLink: "هل نسيت كلمة المرور؟", forgotTitle: "استعادة كلمة المرور", forgotSub: "اكتب بريدك الإلكتروني وسنرسل لك رابطاً لاختيار كلمة مرور جديدة.", send: "إرسال الرابط", sending: "جارٍ الإرسال...", sent: "إذا كان البريد يخص حساباً نشطاً فقد أرسلنا لك رابطاً. تحقق أيضاً من مجلد الرسائل غير المرغوب فيها. تنتهي صلاحيته خلال ساعة واحدة.", back: "العودة إلى تسجيل الدخول", resetTitle: "اختر كلمة مرور جديدة", newPassword: "كلمة المرور الجديدة", repeatPassword: "أعد كتابة كلمة المرور", mismatch: "كلمتا المرور غير متطابقتين.", minLength: "8 أحرف على الأقل.", save: "حفظ كلمة المرور", invalid: "الرابط غير صالح أو منتهي الصلاحية. اطلب رابطاً جديداً.", done: "تم تغيير كلمة المرور. يمكنك تسجيل الدخول الآن.", goLogin: "الذهاب إلى تسجيل الدخول" },
  zh: { forgotLink: "忘记密码？", forgotTitle: "找回密码", forgotSub: "输入您的邮箱，我们会发送一个链接让您设置新密码。", send: "发送链接", sending: "发送中...", sent: "如果该邮箱对应有效账户，我们已向您发送链接。请同时检查垃圾邮件文件夹。链接 1 小时后失效。", back: "返回登录", resetTitle: "设置新密码", newPassword: "新密码", repeatPassword: "再次输入密码", mismatch: "两次输入的密码不一致。", minLength: "至少 8 个字符。", save: "保存密码", invalid: "链接无效或已失效，请重新申请。", done: "完成，您的密码已更改。现在可以登录了。", goLogin: "前往登录" },
};
